apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: authentik
  namespace: apps-authentik
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`account.mircogericke.com`)
    kind: Rule
    services:
    - name: http
      namespace: apps-authentik
      port: http
  tls:
    secretName: certificate-authentik
