apiVersion: v1
kind: Secret
metadata:
    name: authentik-values
    namespace: apps-authentik
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:rN+xeZQDnWyO5kfFu6ePEVE1hkzrTa3cmgPJd4IMsHPOv40HSbRrtuW50BIevtm1U6qj/DSkvunbX8eEiPk6WQgnh+F5MWcofkP/4GWOI8UnP500xXOGGF9KRBUBsOB+Vxg0UqT8524F8cyg4CSd2bmGFBPu/acZQMCKaKWMHdGTVijPhdMfAlRYPjFdkpSn/y8WRLgw4jb/FRWFa3aquidDsEIfeJQzeGudMDYiaivwcMl4A5Ev/Wbiov96lmHJ/qrdmFxyOkQZ9e5o0CEVlo02zqTS+zWN0z/zQ7tFcBtusX+Kkp8nVTRk0rB6AUwrmEgHJM3UUZIfiVXTsnnM+UGyaT+kIiEoasyHN2AMVcFNG9rEA5/e90kk6CNOkdUDoLQ8u2NkJuJkVVKPafvtwFaZ6J0beui9ulzPBB9VZ+e3iIuK98CXCY2fQtdQfz3xIYkNqOVadffPF4Ll5g1S65wXoqSU/HdlLrT00ThKMLvp0yr2wRlS31ObUBavYQW0kCpDfsb7ud6So5WTjbC5SzW/2rVWqUL25EfeJxIa7QbFOWUY6gbiNXRVd0rVLDwN9fyLa4xVeBzJo3o9tnVfYD55mRQWBNK9w+2UYkxnAbmY1boNrpq39YbC16vw3hlmhxzBGx1x0obJ3EA5/2xORm4ZaLFKfrBKYVmJKSQZ5zc4qTjIzpyYsM4Hifarc8PS1ordM9t/XIjZ8xX/JzsJSLQxrhwOgAHu/R8iiE5JF0ByDL7pW4vnkZ7sK7GKFCy4f4GFQXbMrBRkKp1Tzaw+MskdZS4BCRnsn8xEkScFaXm+Rzi34sfAY2O24U8p+q28Z90VtWDG/O4H7bMCC7KnNQ4o3KJZyQxt44Y53a21LOWpJeODNMMhQYNH+mJ/uuYNZjslDUpTZpl+R+KZqUmWCDQqCj9zxRtNpYPihFbcuBluWcfy9ijGg6eGUOdNAmZN1yZKdIkGYmP4lFjTM5OBAg==,iv:p+VFpuDkjngIMRoda+2pwiC1sz9Li7PTT4mSvFhMM2g=,tag:DIJ9u2Jhko9yIz60FmKJiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-27T00:11:19Z"
    mac: ENC[AES256_GCM,data:CsSIw4lHkqkAjGye06M4JYrXj1orJPRr13WnU+h3zN+HRkQMYYvUo/rVbGw8A3Hr4awce+X25WbM5mfpM2w0YRRD5YXeVn26Y4BSkQFynpQINGEG6v+eYxIVhT0Gt88MRUodwnouRGPaKT0tH/BHGleYzKbkYBXgvvWpzOGJgYs=,iv:6ys46S1Ha92U7ghYWFgwHH7pqnjxXSuGhvujJVYKLm4=,tag:U41VXV6tg/Y2Rny19k4VGQ==,type:str]
    pgp:
        - created_at: "2022-11-27T00:11:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxyFiOBVKqWBARAAmp/57Ej8PT0csn8m1eTqSxfN7W0VlxBvoCVgUXrvLEmG
            F6Eae6ihOF5xvUPWaIqEa51MvL8OzG2p6WD3sXVD/BLikBl8cU2AEUnud/+i7NTw
            b8GLQGWvpXQU4CrKfrn5LCYpOV1tof6IhI0zcrq4ULEKpduMruWnfMN3qMGKYpPJ
            rBEpMxWSmI83LSFiGSOyqwAPVzydSWpAihhO+SZ4deguUGzTEDo5rPd5OsuHA0/1
            /waT8ZahBj1a04k2M9PAWM8EYtnan3th7umz5xGnb/xDnfjNovAA0j/pePd0zhkq
            qphXQpPewxlWOTMkRQ+0dZprC+0aOVDI2WfCZO/jrRsDL91UUGkvy22AeCa8ucLL
            5BPlZq3WRJtChRAo/ncCiruobmc1WFFsHi8XHm6hdgNXMqWJ8AcGfZpuMjOjrvGG
            dMK2Ou76aBQFHbUS/N+uv2sJXLFc2XkMiV+xgCZskPvhmNGYnKuUBvRPlACkR0+u
            UPMTk9214tnfH/INbC0Eie+qXnQBjJNOvLIu4Z4Wrx9A6FG2aXEprw7tchnyBZjc
            QOHMkqkdK6ACRfTH4W19PwuS45TXCyS4kY9qxknwofJZvZT73jyoiLTMxjI60sMA
            06LIx+MXPBN80wrLlodIIL7uN6leLteLA9ixbokR/JOVFKiKeR71oO42vuZQgYPS
            XgGQWmhyqqcpeJxIAsGn0YjBDxNHvoSou5K+KvNFBxBayDu+0F8ekFrMPZmHz2YJ
            rlIu4sIjPaamK53U21pn1AHNLEkeU2g8sobsF3dI7l1OeNi+RZacrJUQe6v8sTo=
            =Iu7P
            -----END PGP MESSAGE-----
          fp: 4CE8E7F57DD4C58BBC65A48FECB2D6276795C8D9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
