apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/apps/production
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  dependsOn:
  - name: infrastructure
