apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
  namespace: apps-immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-fast
  resources:
    requests:
      storage: 8Gi

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich
  namespace: apps-immich
spec:
  interval: 1h
  chart:
    spec:
      chart: immich
      version: '0.1.3'
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: apps-immich
      interval: 1h
  valuesFrom:
    - kind: Secret
      name: immich-values
