apiVersion: v1
kind: Secret
metadata:
    name: immich-values
    namespace: apps-immich
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:QhlN98W1Ejv7D1SS4wDF+zI71qLUSKVRDn4blgZET9NmVo5lbB50sxkqXLBOQOghOHIRW1mu9dK5PTp+tOjldJAb6PrQJQ18bBm7racMs3V2onTCJOxEJEyro0OHB/FmihfRizQ9toHN/7IWJ7EX2K+y1oCe44XtaljlyI0JRn+pctfqonK+RfCzF1cay6EmUBRVhfLokj7N+ij5g4xwh10NlwNw5vEcMQC3pI8Rs0B73G9Kpmiswo/6gvconrcVU/5ccp58BG0/I4S/TEOnVy8vRi+UtKe7ZE+SXJ6W6G73Q2/hTJrDjA/LMTj5UqmmwTijTESGWxJh2npEHqSjQ4iPRW+UO7zzzQI0GktPR5T5s5SrGAer3qI971/5LEcuEKBwJDqVN6SJOtJvULvBXpfH19icC7Rg9mXmGCTwM4BZAd3V498KEiFZW+ZpA539TOaa31Taxw6ENIg9nojzIyMELFjf/ICyjj+7VjgSHRgEmP9EwSH5wiaET2q2ytUFlt33tmGiQW8960fp9uZXU9qgY593rYjqu2WEGh0Gai30NHepjpeCrEkYe57elsZPO5uELupR7zSdmdcnJPVhq9+/vvLWgEmNmRmBTeFXe2i/0uhroTfK6Iq8/4QEgN6Uqs1GwbMfnEIz5Q3pSYRtQQbKFmb/8TDbktKEH05YhgUpe9IBOXSzhdIX1P3YUbazxFMydb9fXya/qEtlTY5s6MiyYNC997ataJAh4hgYC+PTJqQeWDwV7j+VmG0YZjBKLKx7XllguB9tq0QnbctSNBrCAnqZ48Tsrz0fWjUfcOweL1uGH5aYsn+hyBue7x8t1C4XCVSXSf1oaOKsIF3pXRaCh/gcQzDQpEBarLSYKloaQ6OXsA3ib9puIA08j6IRVleHhfI0Ty6WLKQnbOMzG+ckRAk2PtXOuSLSxPFJMo9dpqzR8Bych8JA+NDLn5TsroCLcGrQA9V9TJoK/k7TBtRPN1xiuViuVHJAYSoKybXJ/iVfe1/DyWrtNHuyJbLcUJyPx+xLwzlzZ3IRLcvvMenxDn45mJLKUU3C4+QHzAKiCBJKHFbsHu+ahmgNehjg7BHcR6g+3NwFgwxiodE4z9yGEtjEXCFHtjFXICEgLFx5u6AJpnlD+JyzKOBt6M/mavII/qUrLjqBRTaa5+aC9d93nDiIPPdGcawX3/SoA56e3821O6ZJ6cZL/r7SgZqMnuKWY6p/aZ6U9Fs9Y+PEWlta24KolIUzAbBsMTKlMmYEuUxvwoHEUmLVe+xRva7JOwMNsSuPOVCi5jmYAnTjmG/TJQylT9fU8yNc,iv:T/uRsYJ5uQ8iu5sNYzDuT3kb1k9O854KXU1n4SZhklk=,tag:Pfa+LqG9upzDS0WOYIKavw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-20T10:27:55Z"
    mac: ENC[AES256_GCM,data:EY51YprejauhUVC1rm+pP4jxBIBoEu5cCkDq0ELd7z67qtZRPTK65v3F7jkrVS28FrmFxU5VMh0qWPz144nGFxg0kwDbjqQzK9dbR1uYk7v0ffkXByaSQud+6lmSarhoKm9rOa9dXF2YIt8X1o85nSLImHhhnWuJC9kj2Ce+UXE=,iv:ktF5mqcbBPz0XBnYIOOvOd0fagh+J4c7iqM6R7AyfuM=,tag:UFjItAhthZlrpt7ptIMsCQ==,type:str]
    pgp:
        - created_at: "2023-08-20T09:15:58Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxyFiOBVKqWBAQ//TJxsDG7dslBEuyOCelr7WE2chsvYABRJTKVc1IbPdMCi
            tR9cva7sHEIsoXhI5KeAQ1JeWN88IHAL+KapkHBASqQqQ40zjvkiT3n8w+XP6BJt
            q7egOcN2e4YbDeZNbifP2SqG20nDdMOFn4BC6EtkHPlx1zcEKgZyNi+t7QD/kx+E
            5QGWwCovXdxlYLjq22eyS/bGTP0Xiq015eeI0AHN3umT64zXyOG8W0NSgPWbzrHG
            Rl1RA4ZDnmGtONAtvrGzw4CApBQFf0rmHsfawE9CH+VXQvS+gGxZb5+OVGjZZvRv
            hC7pGdGZknCk+AF4kLiPi2HTe2yehMYod4+GcusxLzLIOltHVva9a46mOmT2eMM6
            tgefoVIhq3tMbQ6YUxfXbk2GJXz6qpeFUccI0AS/OXE729FJufGqtrQBnMOw+fYv
            BQy2Y07BP+SExW6Lv5VutVxMv3uuJGF6VT84OxD4oHOfvf9zxhh5YRYAHwQtb+NB
            2+ZCDL7ht+usIfhVsjlClutJn6T3uBRku3r6rlRYQ3fBelTsjKmsONyUjUEFbQry
            EYz9bqoQUwJC0sw4+MLC5wRJHw7XDRKRdB8Gh4Gc/b4ZXY1PEPvcbm1Wgvkhj1w7
            ZOEO+8+U9E4AwSnHtpBbBEC4kGKw7ZuuN/YP+Re0VyyfPZ9N7LB59ypLmtY3Ee7S
            XgHmHe+msjrFEDcrfvDZBglf+qGq5Wqcvb9+okaFL3d9/JFh8iraBxj+nUNt4WK0
            kmiSaTgbB3bmanxvTSa6lxx5bvyw8+T0HkNcjJMEWJpUu+r8kgIn3gf1CQv1UbY=
            =c9rP
            -----END PGP MESSAGE-----
          fp: 4CE8E7F57DD4C58BBC65A48FECB2D6276795C8D9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
