apiVersion: v1
kind: Secret
metadata:
    name: immich-values
    namespace: apps-immich
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:vkqD0dQEg8B6Rm3fVPsZr9rVc1JFcv+Zn2zNulGirdEoJFtLJoOrDAbpARfPbtifp6ZTR+jGQA9aB9yKWJcPIcmro2xNFiBKcQbHppQKoH7y3XpRDPndmgmFBEvsYrUkEtE7sjbhJVyaYbztAjXuzOZqYdAYE0A5Ic8fb/DKZlKg7z/Sct7GSYLdJTPTawwHx3zH1ipAKVBn88RjM62ZoKWkj1RRYUvkpgkLeWoDIKHDaowB2TjdgUKAKvBlToasL8qjA/eAtcKDpnHfBnf4Eb3782rCxjEf/iSLtiWw9fy/Y7Iba0xpNuVTRaUb9aA76yhM5AfvQV974BfNxbp6KQWwOgBTtn9V6pug+XsvJx+UVQoiScDNtxPy+NKRV2F61FfeBL/TgIQRX5D3+i9QBfLICSNQyPn42VsBNj9j2+ZtJtuf3XgCdKkpBGZIxY15BYHk2/fTlomjOYJS6+eqR2pmnPpAK5/S8uvxy6UNygVrRPTueQDiP+h70pewrjjrsHPMNxmtI0LNw+l5pLAnPlRfl03QPr56wJp5eeEegx/L5RjmFnC7kZ3bvJJ64NmK46wz6Ewj0EydiPbi8tQ2+4GFDHwey2O2erTsAmrGvHD4vV6dcnQh2dlDQWstVkLuETgVQo9/s4ZXoPQnC8Om1Z/OOuEVw9QPtjhNXfT7wYbn/z/e/MPUGX894ajZMIH5ZijZAwLm4LZ3YKlS7aUkr3j64F9LwvL1S4L9kQQhv+ucRVLFkTy9pn4frYpUDDjT1s0cr3O+rE4rZmVuD2Dh0yJnYn5QNiJmUQOMrNnFVt3yqlDWsjyKICpRFZj0IucRiCr9j4EK1V3jQqetaxlbB13tFhTcRl1Mjdbt3ibMjiIvBKoqSWk=,iv:bFyjwUZWmA1GIE9l5iDVzZmHWnz5lN9j9O8No0cBAGw=,tag:v3CpksibP560gbmTK9ta5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-20T09:37:19Z"
    mac: ENC[AES256_GCM,data:Yxfx4sUjiSZA2xg07pYB5qvePpDXk5saQS/7WsH4uWqo9AMqzFqI6tNi8/y581oqY05kTy9Uwte1FNdq/57dAkK/3p96T+jKWC68CdDDUiRowjyFaUw0Kz6qwHl7h9jquvhs+WKGLt/3gS9Guq7tKf5i9g8YRXUHiV6osuOyCxQ=,iv:u6GUyNurwqE16d+7eQ+Hk8hSQR3+qmIh68CDKeqyR9c=,tag:yaU689pIHtzx4eYEJcD06w==,type:str]
    pgp:
        - created_at: "2023-08-20T09:15:58Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxyFiOBVKqWBAQ//TJxsDG7dslBEuyOCelr7WE2chsvYABRJTKVc1IbPdMCi
            tR9cva7sHEIsoXhI5KeAQ1JeWN88IHAL+KapkHBASqQqQ40zjvkiT3n8w+XP6BJt
            q7egOcN2e4YbDeZNbifP2SqG20nDdMOFn4BC6EtkHPlx1zcEKgZyNi+t7QD/kx+E
            5QGWwCovXdxlYLjq22eyS/bGTP0Xiq015eeI0AHN3umT64zXyOG8W0NSgPWbzrHG
            Rl1RA4ZDnmGtONAtvrGzw4CApBQFf0rmHsfawE9CH+VXQvS+gGxZb5+OVGjZZvRv
            hC7pGdGZknCk+AF4kLiPi2HTe2yehMYod4+GcusxLzLIOltHVva9a46mOmT2eMM6
            tgefoVIhq3tMbQ6YUxfXbk2GJXz6qpeFUccI0AS/OXE729FJufGqtrQBnMOw+fYv
            BQy2Y07BP+SExW6Lv5VutVxMv3uuJGF6VT84OxD4oHOfvf9zxhh5YRYAHwQtb+NB
            2+ZCDL7ht+usIfhVsjlClutJn6T3uBRku3r6rlRYQ3fBelTsjKmsONyUjUEFbQry
            EYz9bqoQUwJC0sw4+MLC5wRJHw7XDRKRdB8Gh4Gc/b4ZXY1PEPvcbm1Wgvkhj1w7
            ZOEO+8+U9E4AwSnHtpBbBEC4kGKw7ZuuN/YP+Re0VyyfPZ9N7LB59ypLmtY3Ee7S
            XgHmHe+msjrFEDcrfvDZBglf+qGq5Wqcvb9+okaFL3d9/JFh8iraBxj+nUNt4WK0
            kmiSaTgbB3bmanxvTSa6lxx5bvyw8+T0HkNcjJMEWJpUu+r8kgIn3gf1CQv1UbY=
            =c9rP
            -----END PGP MESSAGE-----
          fp: 4CE8E7F57DD4C58BBC65A48FECB2D6276795C8D9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
