apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-podinfo
  namespace: default
spec:
  commonName: podinfo.mircogericke.com
  dnsNames:
  - podinfo.mircogericke.com
  issuerRef:
    name: cluster-issuer-letsencrypt
    kind: ClusterIssuer
  secretName: certificate-podinfo

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: podinfo
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`podinfo.mircogericke.com`)
    kind: Rule
    services:
    - name: podinfo
      port: 9898
  tls:
    secretName: certificate-podinfo
