apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: podinfo
      version: '6.2.x'
      sourceRef:
        kind: HelmRepository
        name: podinfo
      interval: 1h
      valuesFiles:
      - values.yaml
