apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jetstack-cert-manager
  namespace: cert-manager
spec:
  interval: 1h
  chart:
    spec:
      chart: cert-manager
      # Check Upgrade Guide: https://cert-manager.io/docs/installation/upgrading/
      version: '1.10.x'
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: default
      interval: 1h
  values:
    installCRDs: true
