apiVersion: projectcontour.io/v1alpha1
kind: ContourDeployment
metadata:
  name: contour-configuration
  namespace: projectcontour
spec:
  contour:
    replicas: 1
  envoy:
    networkPublishing:
      type: NodePortService

---

apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: contour
spec:
  controllerName: projectcontour.io/gateway-controller
  parametersRef:
    kind: ContourDeployment
    group: projectcontour.io
    namespace: projectcontour
    name: contour-configuration
