apiVersion: v1
kind: Namespace
metadata:
  name: projectcontour
  labels:
    pod-security.kubernetes.io/enforce: privileged

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour
  namespace: projectcontour
spec:
  interval: 1h
  chart:
    spec:
      chart: contour
      version: '10.0.x'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
      interval: 1h
  values:
    envoy:
      service:
        type: NodePort