apiVersion: v1
kind: Namespace
metadata:
  name: traefik-system

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 1h
  chart:
    spec:
      chart: traefik
      version: '20.x.x'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik-system
      interval: 1h
  values:
    deployment:
      kind: DaemonSet
    ingressRoute:
      dashboard:
        enabled: false
    ports:
      websecure:
        http3:
          enabled: true
    service:
      spec:
        loadBalancerIP: "10.0.10.0"
