apiVersion: v1
kind: Namespace
metadata:
  name: apps-authentik

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-authentik
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/apps/production/authentik
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
