apiVersion: v1
kind: Namespace
metadata:
  name: apps-legacy-server

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: deployment
  namespace: apps-legacy-server
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/apps/production/legacy-server
  prune: true
